[package]
name = "lace_consts"
version = "0.1.0"
authors = ["Promied AI"]
edition = "2021"
license = "SSPL-1.0"
homepage = "https://www.lace.dev/"
repository = "https://github.com/promised-ai/lace"
description = "Default constants for Lace"

[dependencies]
rv = { version = "0.15.0", features = ["serde1", "arraydist"] }
